# Generated by Django 5.1.2 on 2024-10-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='userPhotos'),
        ),
    ]
