# Generated by Django 5.1.2 on 2024-10-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_gender_useraccount_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_general_member',
            field=models.BooleanField(default=False),
        ),
    ]
